### PR TITLE
Fixed issue with custom handler being overridden in the compiler pass

### LINKED ISSUE #89: Handler is overwritten when using middleware.
Currently, if you set a service ID for the `config.handler` key of a guzzle client, it is overridden in the compiler pass.

https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/DependencyInjection/CompilerPass/MiddlewarePass.php#L106

This is not the correct behavior, and should be fixed. The handler provided by the user should have the middleware injected.

### PR DESCRIPTION
**Pull request by csarrazi**
This PR fixes #89.

The handler is now no longer overwritten when middleware are injected.

### CODE REVIEW

**Comment by SofHad** [comment]
:+1:

File: src/DependencyInjection/CompilerPass/MiddlewarePass.php [hunk 1]
```diff
@@ -116,7 +105,21 @@ private function registerMiddleware(ContainerBuilder $container, array $middlewa
...
+                $clientHandlerStackId = sprintf('csa_guzzle.handler_stack.%s', $clientId);
+
+                $container->setDefinition($clientHandlerStackId, $handlerStack);
+                $options['handler'] = $handlerStack;
+            }
+
+            $handlerStack = $options['handler'];
+
+            foreach ($clientMiddleware as $middleware) {
+                $handlerStack->addMethodCall('push', [new Reference($middleware['id']), $middleware['alias']]);
```
Comment (Tobion) [inline src/DependencyInjection/CompilerPass/MiddlewarePass.php]: This is not safe to call on the handler. `$options['handler']` is just a callable by definition. It is a `HandlerStack` by default but not necessarily for custom handlers. So `push` might not exist.

Comment (Tobion) [inline src/DependencyInjection/CompilerPass/MiddlewarePass.php]: So if its not a HandlerStack you could wrap the custom handler in a HandlerStack first.
